# Generated by Django 5.2.6 on 2025-09-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
