# Generated by Django 5.2.6 on 2026-01-10 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_bodymeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
