# Generated by Django 5.2.6 on 2026-01-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_bodymeasurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
